baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = ["hugo-admonitions", "LoveIt"]

[menu]
  [[menu.main]]
    weight = 1
	identifier = "posts"
	name = "Posts"
	url = "/posts"
  [[menu.main]]
    weight = 2
	identifier = "tags"
	name = "Tags"
	url = "/tags"

[markup]
  [markup.highlight]
    noClasses = false
